# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "puma", "~> 4.3"

gem "rerun", "~> 0.13.0"

gem "rubocop", "~> 0.82.0"

gem "roda", "~> 3.31"

gem "tilt", "~> 2.0"
